#!/bin/bash
set -eux

# Clean apt caches
apt autoremove -y && apt-get clean || true

# Remove random seed to get it recreated
rm -f /var/lib/systemd/random-seed || true

# Remove SSH host keys so they will be generated on first boot
rm -f /etc/ssh/ssh_host_* || true

# Clean cloud-init state and logs
cloud-init clean --logs --machine-id || true

# Clear command history
rm -f /root/.bash_history || true
